apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
      sealedsecrets.bitnami.com/namespace-wide: "true"
  name: {{ template "campville.name" . }}-secrets
spec:
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: {{ template "campville.name" . }}-secrets
  encryptedData:
{{ (.Files.Get (include "campville.path.secrets" . )) | indent 4 }}